# Generated by Django 3.2.5 on 2021-07-29 13:37

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_user',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False)),
                ('ftpUsername', models.CharField(max_length=100, unique=True)),
                ('ftpPassword', models.CharField(max_length=200)),
                ('ftpHomeDir', models.FilePathField()),
                ('actif', models.PositiveSmallIntegerField(default=1)),
                ('dateCreation', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateExpiration', models.DateTimeField()),
                ('dateAcces', models.DateTimeField()),
                ('nom', models.CharField(max_length=20)),
                ('societe', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('permanent', models.PositiveSmallIntegerField(default=1)),
                ('ftpGroup', models.CharField(max_length=200)),
                ('idAdministrateur', models.PositiveSmallIntegerField(default=8)),
                ('contact_interne', models.CharField(max_length=255)),
                ('filewatch_enable', models.PositiveSmallIntegerField(default=1)),
                ('filewatch_contact', models.CharField(max_length=255)),
                ('autodel_enable', models.PositiveSmallIntegerField(default=1)),
                ('autodel_range', models.IntegerField(default=11)),
                ('autoresetpass_enable', models.IntegerField(default=10)),
                ('autoresetpass_period', models.IntegerField(default=10)),
            ],
        ),
    ]
