# Generated by Django 3.2.5 on 2021-09-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user',
            name='actif',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Actif'), (0, 'Inactif')], default=1),
        ),
        migrations.AlterField(
            model_name='t_user',
            name='autodel_enable',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Actif'), (0, 'Inactif')], default=1),
        ),
        migrations.AlterField(
            model_name='t_user',
            name='filewatch_enable',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Actif'), (0, 'Inactif')], default=1),
        ),
    ]
