# Generated by Django 3.2.5 on 2021-09-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0002_auto_20210902_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user',
            name='ftpHomeDir',
            field=models.CharField(max_length=800),
        ),
    ]
