# Generated by Django 3.2.5 on 2021-09-09 22:16

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0003_alter_t_user_ftphomedir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
