# Generated by Django 3.2.5 on 2021-09-10 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0005_alter_t_user_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user',
            name='contact_interne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='t_user',
            name='dateAcces',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_user',
            name='dateExpiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 0, 0)),
        ),
        migrations.AlterField(
            model_name='t_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='t_user',
            name='ftpGroup',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
