# Generated by Django 3.2.5 on 2021-09-30 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0006_auto_20210910_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user',
            name='dateExpiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 13, 57, 23, 202379)),
        ),
        migrations.AlterField(
            model_name='t_user',
            name='ftpHomeDir',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='t_user',
            name='ftpPassword',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='t_user',
            name='idUser',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
