# Generated by Django 3.2.5 on 2021-09-30 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0007_auto_20210930_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user',
            name='dateExpiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 0, 0)),
        ),
    ]
